### ISSUE TITLE
Sitemap maken

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/component-library#106]
Vladimir voegt refinement toe

```[tasklist]
### Tasks
```

**Comment by iamskip** [comment]
De sitemap is gebaseerd op de structuur bedacht door de UX designer en de contentmanagers. Je kunt de sitemap hier vinden: 
[ Link naar FlowmapApp
](https://app.flowmapp.com/share/projects/c680676c-3bf3-42ea-b503-e2dad2509d2f/sitemap/bc072eb2-81fd-41c7-af77-f32facdb7091)
Deze sitemap is echter flexibel en kan worden aangepast op basis van nieuwe inzichten die voortkomen uit gebruikersonderzoek.
