### ISSUE TITLE
Componenten veranderen in documentatie in menu

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/component-library#40]
Typography en Templates horen niet in de lijst van componenten. Deze moeten ergens anders komen te staan. Vladimir bedenkt plan met foundations/componenten/templates.
```[tasklist]
### Tasks
- [x] Plan bedenken
- [x] Ontwerpen
- [x] Overdragen aan Woweb en devops
```

**Comment by iamskip** [comment]
@Michel-Verhoeven 
De structuur die we in Figma hebben, willen we ook in de componentbibliotheek hebben:

- Documentatie
- Ontwerpbasis
- Componenten
- Templates
